config/routes.rb
FobhApp::Application.routes.draw do
  
  get "users/new"

  root :to => 'pages#home'
  

  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/events', :to => 'pages#events'
  match '/publications', :to => 'pages#publications'
  match '/signup', :to =>'users#new'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  @title="Home"
  end

  def about
  @title="About"
  end

  def contact
  @title="Contact"
  end

  def events
  @title="Events"
  end

  def publications
  @title="Publications"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @title="Sign Up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

#Return a title on a per page basis

def title
 base_title="Discover Box Hill"
  if @title.nil?
   base_title
  else
   "#{base_title} | #{@title}"
  end
end



end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>

<div class="space"> 
</div>
<div class="bottom_section"> 
<nav>
    <ul>
      <li><%= link_to "Map", "#" %></li>
      <li><%= link_to "News", "#" %></li>
      <li><a href="http://friendsofboxhill.blogspot.com/">Blog</a></li>
      <li><a href="http://www.youtube.com/user/FRIENDSOFBOXHILL/">Youtube</a></li>
    </ul>
  </nav>
</div>



<div class="space"> 
</div> 

</footer>

app/views/layouts/_header.html.erb
<header>


<p class="tagline">Welcome to the Friends Of Box Hill Website</p>



<div class="title_section">
<%=image_tag("fobh-boxtree.jpg", :alt=>"Coursework App")%>
</div>


<div class="space">
<nav>
<ul>
<li><%=link_to "Home", root_path%></li>
<li><%=link_to "About", about_path%></li>
<li><%=link_to "Events", events_path%></li>
<li><%=link_to "Publications", publications_path%></li>
<li><%=link_to "Contact Us", contact_path%></li>
<li><%=link_to "Sign in", "#"%></li>
<li><%=link_to "Register", signup_path%></li>

</ul>
</nav>
</div>


</header>










 

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Framework CSS --> 
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>

<!-- Import fancy-type plugin. -->  
<%= stylesheet_link_tag 'blueprint/plugins/fancy-type/screen',  :media => 'screen' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=title%></title>
  <%= csrf_meta_tags %>
  <%= render 'layouts/stylesheets' %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
</head>

<body>
<div class="container">
<%= render 'layouts/header' %>
<section>
<%= yield %>
</section>
<%= render 'layouts/footer' %>
</div>
</body>
</html>
	

app/views/pages/about.html.erb
<h1>About</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<a href="http://news.railstutorial.org/">Youtube</a>
<%= link_to "Contact", contact_path %>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/events.html.erb
<h1>Events</h1>
<p>Find me in app/views/pages/events.html.erb</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/publications.html.erb
<h1>Publications</h1>
<p>Find me in app/views/pages/findus.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>